services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=pass
    ports:
      - "5341:80"
    restart: unless-stopped
    
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: marketwizard
    ports:
      - "5432:5432"
#  marketwizardapi:
#    image: marketwizardapi
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres

